version: "3"

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube-app
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar_pass
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: postgres_sonar
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar_pass
      - POSTGRES_DB=sonar
    volumes:
      - sonarqube_db:/var/lib/postgresql/data

volumes:
  sonarqube_db:
